In [1]:
!pip install numpy


[notice] A new release of pip is available: 23.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [4]:
%timeit [i**2 for i in lst]

6.97 µs ± 105 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
arr = np.array(lst)

In [7]:
%timeit arr**2

1.72 µs ± 28.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [8]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [9]:
lst + 1

TypeError: can only concatenate list (not "int") to list

In [11]:
k = []

for i in lst:
    k.append(i+1)

In [12]:
k

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [13]:
[i+1 for i in  lst]

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [14]:
lst + [1]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1]

In [15]:
arr + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
j = np.array(42)

In [18]:
j.ndim

0

In [19]:
l = [1,2,3,4,5]

In [20]:
arr = np.array(l)

In [21]:
arr

array([1, 2, 3, 4, 5])

In [22]:
arr.ndim

1

In [23]:
type(arr)

numpy.ndarray

In [24]:
arr.shape

(5,)

In [25]:
j.shape

()

In [28]:
new_arr = np.arange(3,12,2)

In [29]:
new_arr

array([ 3,  5,  7,  9, 11])

In [31]:
lst_2d = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [33]:
arr_2d = np.array(lst_2d)

In [34]:
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [35]:
arr_2d.ndim

2

In [36]:
arr_2d.shape

(4, 3)

In [39]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
np.ones((7,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [45]:
np.diag([1,5,9])

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [46]:
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [47]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
new_arr = np.random.randint(10,100, (5,4))

In [51]:
new_arr.shape

(5, 4)

In [52]:
new_arr[0]

array([40, 44, 74, 39])

In [53]:
new_arr

array([[40, 44, 74, 39],
       [30, 61, 16, 55],
       [37, 35, 82, 92],
       [49, 10, 51, 49],
       [60, 15, 54, 83]])

In [54]:
new_arr[2]

array([37, 35, 82, 92])

In [55]:
new_arr[-2]

array([49, 10, 51, 49])

In [56]:
new_arr[-1]

array([60, 15, 54, 83])

In [57]:
new_arr

array([[40, 44, 74, 39],
       [30, 61, 16, 55],
       [37, 35, 82, 92],
       [49, 10, 51, 49],
       [60, 15, 54, 83]])

In [59]:
new_arr[0,0]

40

In [60]:
new_arr[2,2]

82

In [62]:
new_arr[4,3]

83

In [63]:
new_arr

array([[40, 44, 74, 39],
       [30, 61, 16, 55],
       [37, 35, 82, 92],
       [49, 10, 51, 49],
       [60, 15, 54, 83]])

In [66]:
new_arr[2:, 1:]

array([[35, 82, 92],
       [10, 51, 49],
       [15, 54, 83]])

In [67]:
new_arr[:,-1]

array([39, 55, 92, 49, 83])

In [70]:
new_arr[0,0] = 400

In [71]:
new_arr

array([[400,  44,  74,  39],
       [ 30,  61,  16,  55],
       [ 37,  35,  82,  92],
       [ 49,  10,  51,  49],
       [ 60,  15,  54,  83]])

In [74]:
mask = new_arr>10

In [75]:
print(mask)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True False  True  True]
 [ True  True  True  True]]


In [76]:
np.sum(mask)

19

In [79]:
np.sum(new_arr>10)

19

In [81]:
new_arr[mask]

array([400,  44,  74,  39,  30,  61,  16,  55,  37,  35,  82,  92,  49,
        51,  49,  60,  15,  54,  83])

In [83]:
new_arr[new_arr>10]

array([400,  44,  74,  39,  30,  61,  16,  55,  37,  35,  82,  92,  49,
        51,  49,  60,  15,  54,  83])

In [89]:
new_arr[2:,-2:] = 0

In [90]:
new_arr

array([[400,  44,  74,  39],
       [ 30,  61,  16,  55],
       [ 37,  35,   0,   0],
       [ 49,  10,   0,   0],
       [ 60,  15,   0,   0]])

In [92]:
a = np.array([10,20,30,40])

In [94]:
b = np.arange(1,5)

In [95]:
a

array([10, 20, 30, 40])

In [96]:
b

array([1, 2, 3, 4])

In [97]:
a+b

array([11, 22, 33, 44])

In [98]:
a-b

array([ 9, 18, 27, 36])

In [99]:
a*b

array([ 10,  40,  90, 160])

In [100]:
a/b

array([10., 10., 10., 10.])

In [101]:
b**2

array([ 1,  4,  9, 16], dtype=int32)

In [102]:
a>15

array([False,  True,  True,  True])

In [103]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945])

In [104]:
np.sin(b)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [107]:
A = np.random.randint(0,5,size = (3,4))

In [109]:
B = np.random.randint(0,5, (4,3))

In [110]:
np.dot(A,B)

array([[ 6, 20, 10],
       [ 8, 37, 18],
       [12, 21, 12]])

In [112]:
A = np.arange(0,24)

In [113]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [115]:
A = A.reshape(6,4)

In [116]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [117]:
np.sqrt(A)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152]])

In [118]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [119]:
np.sum(A)

276

In [120]:
np.min(A)

0

In [121]:
np.max(A)

23

In [122]:
np.mean(A)

11.5

In [123]:
np.std(A)

6.922186552431729

In [124]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [126]:
np.sum(A, axis=0)

array([60, 66, 72, 78])

In [127]:
np.sum(A,axis=1)

array([ 6, 22, 38, 54, 70, 86])

In [128]:
np.mean(A,axis=0)

array([10., 11., 12., 13.])

In [129]:
np.mean(A,axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5, 21.5])

In [130]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [131]:
A.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [132]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [133]:
A.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [135]:
A.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [136]:
np.transpose(A)

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [137]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [138]:
np.transpose(A)

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [140]:
a =np.random.randint(0,10,(2,2))

In [142]:
b = np.random.randint(0,10,(2,2))

In [143]:
a

array([[7, 0],
       [0, 3]])

In [144]:
b

array([[7, 7],
       [5, 9]])

In [146]:
np.vstack((a,b))

array([[7, 0],
       [0, 3],
       [7, 7],
       [5, 9]])

In [148]:
np.hstack((a,b))

array([[7, 0, 7, 7],
       [0, 3, 5, 9]])

In [150]:
a = np.random.randint(0,10,(3,3))

In [151]:
b = np.random.randint(0,10,(4,4))

In [152]:

a

array([[5, 0, 5],
       [0, 9, 8],
       [2, 7, 1]])

In [153]:
b

array([[9, 8, 0, 5],
       [8, 3, 0, 7],
       [5, 4, 8, 9],
       [3, 5, 6, 2]])

In [154]:
a+b

ValueError: operands could not be broadcast together with shapes (3,3) (4,4) 

In [155]:
a

array([[5, 0, 5],
       [0, 9, 8],
       [2, 7, 1]])

In [156]:
b = np.array([1,2,3])

In [157]:
a

array([[5, 0, 5],
       [0, 9, 8],
       [2, 7, 1]])

In [158]:
b

array([1, 2, 3])

In [159]:
a.shape

(3, 3)

In [160]:
b.shape

(3,)

In [161]:
a+b

array([[ 6,  2,  8],
       [ 1, 11, 11],
       [ 3,  9,  4]])

In [162]:
a-b

array([[ 4, -2,  2],
       [-1,  7,  5],
       [ 1,  5, -2]])

In [163]:
a*b

array([[ 5,  0, 15],
       [ 0, 18, 24],
       [ 2, 14,  3]])

In [164]:
a/b

array([[5.        , 0.        , 1.66666667],
       [0.        , 4.5       , 2.66666667],
       [2.        , 3.5       , 0.33333333]])

In [169]:
a + b.T

array([[ 6,  2,  8],
       [ 1, 11, 11],
       [ 3,  9,  4]])

In [168]:
b.T

array([1, 2, 3])

In [170]:
a

array([[5, 0, 5],
       [0, 9, 8],
       [2, 7, 1]])

In [171]:
a+5

array([[10,  5, 10],
       [ 5, 14, 13],
       [ 7, 12,  6]])

In [172]:
p1  = np.array([1,2,4,7,-2,9,6,0])

In [173]:
p2  = np.array([5,5,8,2,-9,2,1,6])

In [174]:
p1

array([ 1,  2,  4,  7, -2,  9,  6,  0])

In [175]:
p2

array([ 5,  5,  8,  2, -9,  2,  1,  6])

In [181]:
np.sqrt(np.sum((p2-p1)**2))

15.0

In [182]:
def distance(p1,p2):
    return np.sqrt(np.sum((p2-p1)**2))

In [183]:
distance(p1,p2)

15.0

In [184]:
p1

array([ 1,  2,  4,  7, -2,  9,  6,  0])

In [185]:
p2

array([ 5,  5,  8,  2, -9,  2,  1,  6])

In [187]:
s = 0
for i in range(8):
    s+=(p2[i] - p1[i])**2
    
print(s**0.5)

15.0


In [188]:
#Assignment

In [189]:
!pip install pandas

In [190]:
import pandas as pd

In [191]:
o = ['c++', 'java', 'python', 'javscript']

In [192]:
type(o)

list

In [194]:
n = pd.Series(o)

In [195]:
type(n)

pandas.core.series.Series

In [196]:
n

0          c++
1         java
2       python
3    javscript
dtype: object

In [197]:
n[2]

'python'

In [198]:
n[3]

'javscript'

In [199]:
n[0]

'c++'

In [203]:
n.index = ['a', 'b', 'c', 'd']

In [204]:
n

a          c++
b         java
c       python
d    javscript
dtype: object

In [205]:
n[2]

'python'

In [206]:
n['c']

'python'

In [207]:
import numpy as np

In [210]:
arr = np.random.randint(10,100, size = (6,4))

In [211]:
arr

array([[69, 11, 91, 69],
       [93, 51, 53, 32],
       [93, 10, 16, 44],
       [73, 89, 68, 41],
       [34, 74, 85, 79],
       [51, 89, 91, 61]])

In [213]:
df = pd.DataFrame(data=arr)

In [214]:
type(df)

pandas.core.frame.DataFrame

In [216]:
df[2]

0    91
1    53
2    16
3    68
4    85
5    91
Name: 2, dtype: int32

In [217]:
df[3]

0    69
1    32
2    44
3    41
4    79
5    61
Name: 3, dtype: int32

In [219]:
type(df[0])

pandas.core.series.Series

In [222]:
df.columns = ['A','B', 'C', 'D']

In [223]:
df

A   B   C   D
0  69  11  91  69
1  93  51  53  32
2  93  10  16  44
3  73  89  68  41
4  34  74  85  79
5  51  89  91  61

In [224]:
df['D']

0    69
1    32
2    44
3    41
4    79
5    61
Name: D, dtype: int32

In [225]:

df['C']

0    91
1    53
2    16
3    68
4    85
5    91
Name: C, dtype: int32

In [226]:
df.shape

(6, 4)

In [230]:
df.head(3)

A   B   C   D
0  69  11  91  69
1  93  51  53  32
2  93  10  16  44

In [231]:
df.tail(6)

A   B   C   D
0  69  11  91  69
1  93  51  53  32
2  93  10  16  44
3  73  89  68  41
4  34  74  85  79
5  51  89  91  61

In [232]:
df['C']

0    91
1    53
2    16
3    68
4    85
5    91
Name: C, dtype: int32

In [234]:
df[['C', 'D']]

C   D
0  91  69
1  53  32
2  16  44
3  68  41
4  85  79
5  91  61

In [237]:
df[['D','B','C']]

D   B   C
0  69  11  91
1  32  51  53
2  44  10  16
3  41  89  68
4  79  74  85
5  61  89  91

In [238]:
df

A   B   C   D
0  69  11  91  69
1  93  51  53  32
2  93  10  16  44
3  73  89  68  41
4  34  74  85  79
5  51  89  91  61

In [239]:
df['A+B'] = df['A'] + df['B']

In [240]:
df


A   B   C   D  A+B
0  69  11  91  69   80
1  93  51  53  32  144
2  93  10  16  44  103
3  73  89  68  41  162
4  34  74  85  79  108
5  51  89  91  61  140

In [243]:
df['C*D'] = df['C'] * df['D']

In [244]:
df

A   B   C   D  A+B   C*d   C*D
0  69  11  91  69   80  6279  6279
1  93  51  53  32  144  1696  1696
2  93  10  16  44  103   704   704
3  73  89  68  41  162  2788  2788
4  34  74  85  79  108  6715  6715
5  51  89  91  61  140  5551  5551

In [248]:
df.drop('C*d', axis=1, inplace=True)

In [249]:
df

A   B   C   D  A+B   C*D
0  69  11  91  69   80  6279
1  93  51  53  32  144  1696
2  93  10  16  44  103   704
3  73  89  68  41  162  2788
4  34  74  85  79  108  6715
5  51  89  91  61  140  5551

In [252]:
df.drop(labels=['C', 'A+B'], axis=1, inplace=True)

In [253]:
df

A   B   D   C*D
0  69  11  69  6279
1  93  51  32  1696
2  93  10  44   704
3  73  89  41  2788
4  34  74  79  6715
5  51  89  61  5551

In [255]:
df.index = 'p q r s t u'.split()

In [256]:
df

A   B   D   C*D
p  69  11  69  6279
q  93  51  32  1696
r  93  10  44   704
s  73  89  41  2788
t  34  74  79  6715
u  51  89  61  5551

In [257]:
df.loc['r']

A       93
B       10
D       44
C*D    704
Name: r, dtype: int32

In [258]:
df.loc['u']

A        51
B        89
D        61
C*D    5551
Name: u, dtype: int32

In [259]:
df.iloc[2]

A       93
B       10
D       44
C*D    704
Name: r, dtype: int32

In [260]:
df.iloc[-1]

A        51
B        89
D        61
C*D    5551
Name: u, dtype: int32

In [261]:
df.iloc[5]

A        51
B        89
D        61
C*D    5551
Name: u, dtype: int32

In [265]:
df

A   B   D   C*D
p  69  11  69  6279
q  93  51  32  1696
r  93  10  44   704
s  73  89  41  2788
t  34  74  79  6715
u  51  89  61  5551

In [273]:
df.iloc[3:,1:]

B   D   C*D
s  89  41  2788
t  74  79  6715
u  89  61  5551

In [274]:
df.iloc[-2:,-3:]

B   D   C*D
t  74  79  6715
u  89  61  5551

In [284]:
df.iloc[2:-2, 1:][['B', 'D']]

B   D
r  10  44
s  89  41

In [289]:
type(df.iloc[-2:][['D']])

pandas.core.frame.DataFrame

In [292]:
type(df.iloc[-2:]['B'])


pandas.core.series.Series

In [293]:
df


A   B   D   C*D
p  69  11  69  6279
q  93  51  32  1696
r  93  10  44   704
s  73  89  41  2788
t  34  74  79  6715
u  51  89  61  5551

In [295]:
mask = df>30

In [296]:
mask

A      B     D   C*D
p  True  False  True  True
q  True   True  True  True
r  True  False  True  True
s  True   True  True  True
t  True   True  True  True
u  True   True  True  True

In [297]:
df[mask]

A     B   D   C*D
p  69   NaN  69  6279
q  93  51.0  32  1696
r  93   NaN  44   704
s  73  89.0  41  2788
t  34  74.0  79  6715
u  51  89.0  61  5551

In [299]:
df[df>30]

A     B   D   C*D
p  69   NaN  69  6279
q  93  51.0  32  1696
r  93   NaN  44   704
s  73  89.0  41  2788
t  34  74.0  79  6715
u  51  89.0  61  5551

In [306]:
df[df['B']>40][['B', 'D']]

B   D
q  51  32
s  89  41
t  74  79
u  89  61

In [307]:
df['A']>40

p     True
q     True
r     True
s     True
t    False
u     True
Name: A, dtype: bool

In [309]:
df['D']<50

p    False
q     True
r     True
s     True
t    False
u    False
Name: D, dtype: bool

In [315]:
df[(df['A']>40) & (df['D']<50)]

A   B   D   C*D
q  93  51  32  1696
r  93  10  44   704
s  73  89  41  2788

In [316]:
df

A   B   D   C*D
p  69  11  69  6279
q  93  51  32  1696
r  93  10  44   704
s  73  89  41  2788
t  34  74  79  6715
u  51  89  61  5551

In [318]:
df_array = df.values

In [319]:
df_array

array([[  69,   11,   69, 6279],
       [  93,   51,   32, 1696],
       [  93,   10,   44,  704],
       [  73,   89,   41, 2788],
       [  34,   74,   79, 6715],
       [  51,   89,   61, 5551]])

In [322]:
ls

 Volume in drive C is OS
 Volume Serial Number is 0CC1-C20F

 Directory of C:\Users\skme2\Downloads

23-06-2023  20:36    <DIR>          .
12-06-2023  12:12    <DIR>          ..
23-06-2023  19:46    <DIR>          .ipynb_checkpoints
28-03-2023  16:40            26,071 01_Loops_Practice_04_05.ipynb
02-11-2022  15:49           410,816 0211resume.pdf
20-03-2023  16:51           118,844 04_06.ipynb
08-04-2023  17:46             6,413 08_04_2023_window functions__damini_04_06.sql
08-05-2023  17:43           453,229 08_05_power bi.pbix
08-11-2022  11:41           412,631 08novresume.pdf
09-04-2023  17:37             2,262 09_damini stored_processor.sql
08-10-2022  12:44               582 1.0.5
11-04-2023  14:25       279,467,547 10_04_2023.mp4
16-09-2022  19:48         7,070,153 100-Business-English-Expressions.pdf
23-09-2022  08:41         1,139,062 101-Essays-That-Will-Change-The-Way-You-Think_.pdf
03-01-2023  14:28    <DIR>          1071244354_9761672683050
03-01-2023  14:23            27

22-04-2023  16:43             8,347 dataexcel (1).xlsx
22-04-2023  16:42             9,286 dataexcel.xlsx
13-09-2022  21:40        24,741,696 dataset (1).rar
02-01-2023  15:48            28,209 dataset issue.png
13-09-2022  21:39        24,741,696 dataset.rar
27-04-2023  16:32    <DIR>          data-society-global-terrorism-data
31-03-2023  20:14           118,690 Dax 2.pbix
31-03-2023  18:08           430,086 DAX.pbix
11-10-2022  13:38         2,493,152 Day04-Docker-20221011T080805Z-001.zip
07-01-2023  13:33            31,303 ddddddWRrrrrrrr.png
05-08-2022  11:46         1,569,899 Deep learning (2).pdf
01-08-2022  14:05           378,488 Deep Learning.pdf
06-12-2022  14:50    <DIR>          Deployement
27-09-2022  18:35    <DIR>          Diabetes-prediction-project-main
27-09-2022  18:35         1,576,224 Diabetes-prediction-project-main.zip
27-09-2022  18:34           510,271 diabetes-prediction-rfc-model.pkl
08-01-2023  13:06           546,634 Dissertation.pptx
09-09-2022  21:49    

In [324]:
df = pd.read_csv('https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv')

In [325]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [326]:
type(df)

pandas.core.frame.DataFrame

In [329]:
df.head(2)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [330]:
df.tail(8)

sepal_length  sepal_width  petal_length  petal_width    species
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [334]:
df.sample(5)

sepal_length  sepal_width  petal_length  petal_width    species
139           6.9          3.1           5.4          2.1  virginica
117           7.7          3.8           6.7          2.2  virginica
147           6.5          3.0           5.2          2.0  virginica
42            4.4          3.2           1.3          0.2     setosa
33            5.5          4.2           1.4          0.2     setosa

In [335]:
df.shape

(150, 5)

In [336]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [337]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [338]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [339]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [340]:
df.describe(include='all')

sepal_length  sepal_width  petal_length  petal_width    species
count     150.000000   150.000000    150.000000   150.000000        150
unique           NaN          NaN           NaN          NaN          3
top              NaN          NaN           NaN          NaN  virginica
freq             NaN          NaN           NaN          NaN         50
mean        5.843333     3.054000      3.758667     1.198667        NaN
std         0.828066     0.433594      1.764420     0.763161        NaN
min         4.300000     2.000000      1.000000     0.100000        NaN
25%         5.100000     2.800000      1.600000     0.300000        NaN
50%         5.800000     3.000000      4.350000     1.300000        NaN
75%         6.400000     3.300000      5.100000     1.800000        NaN
max         7.900000     4.400000      6.900000     2.500000        NaN

In [342]:
df['species'].nunique()

3

In [345]:
df.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [350]:
df[df.species == 'versicolor'].shape

(50, 5)

In [354]:
df.species.value_counts()['virginica']

50

In [355]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [356]:
df.sepal_length.mean()

5.843333333333335

In [357]:
df['sepal_length'].mean()

5.843333333333335

In [358]:
df.petal_width.max()

2.5

In [359]:
df['petal_width'].sum()

179.8

In [360]:
df.petal_width.min()

0.1

In [362]:
df.sort_index()

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [368]:
df.sort_values(by=['sepal_length', 'sepal_width'], ascending=[False, True], inplace=True)

In [369]:
df

sepal_length  sepal_width  petal_length  petal_width    species
131           7.9          3.8           6.4          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
..            ...          ...           ...          ...        ...
41            4.5          2.3           1.3          0.3     setosa
8             4.4          2.9           1.4          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
42            4.4          3.2           1.3          0.2     setosa
13            4.3          3.0           1.1          0.1     setosa

[150 rows x 5 columns]

In [372]:
df.species.apply(len)

131    9
118    9
122    9
135    9
117    9
      ..
41     6
8      6
38     6
42     6
13     6
Name: species, Length: 150, dtype: int64

In [374]:
df.sort_index()

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [375]:
df.apply(lambda x:x+x)

sepal_length  sepal_width  petal_length  petal_width             species
131          15.8          7.6          12.8          4.0  virginicavirginica
118          15.4          5.2          13.8          4.6  virginicavirginica
122          15.4          5.6          13.4          4.0  virginicavirginica
135          15.4          6.0          12.2          4.6  virginicavirginica
117          15.4          7.6          13.4          4.4  virginicavirginica
..            ...          ...           ...          ...                 ...
41            9.0          4.6           2.6          0.6        setosasetosa
8             8.8          5.8           2.8          0.4        setosasetosa
38            8.8          6.0           2.6          0.4        setosasetosa
42            8.8          6.4           2.6          0.4        setosasetosa
13            8.6          6.0           2.2          0.2        setosasetosa

[150 rows x 5 columns]

In [381]:
df[df.species == 'virginica']['sepal_length'].min()

4.9

In [388]:
df.aggregate(['min','max', 'std', 'mean', 'median'])

sepal_length  sepal_width  petal_length  petal_width    species
min         4.300000     2.000000      1.000000     0.100000     setosa
max         7.900000     4.400000      6.900000     2.500000  virginica
std         0.828066     0.433594      1.764420     0.763161        NaN
mean        5.843333     3.054000      3.758667     1.198667        NaN
median      5.800000     3.000000      4.350000     1.300000        NaN

In [391]:
obj = df.groupby('species')

In [392]:
obj.mad()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa           0.27072      0.28888       0.13088      0.08384
versicolor       0.42144      0.25480       0.37920      0.15712
virginica        0.50256      0.24216       0.44000      0.22808

In [393]:
obj.max()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa               5.8          4.4           1.9          0.6
versicolor           7.0          3.4           5.1          1.8
virginica            7.9          3.8           6.9          2.5

In [394]:
obj.min()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa               4.3          2.3           1.0          0.1
versicolor           4.9          2.0           3.0          1.0
virginica            4.9          2.2           4.5          1.4

In [395]:
obj.median()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa               5.0          3.4          1.50          0.2
versicolor           5.9          2.8          4.35          1.3
virginica            6.5          3.0          5.55          2.0

In [396]:
obj.mean()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa             5.006        3.418         1.464        0.244
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [401]:
df[df.species == 'setosa']['petal_length'].mean()

1.4639999999999997

In [402]:
obj.count()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa                50           50            50           50
versicolor            50           50            50           50
virginica             50           50            50           50

In [403]:
obj.sum()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa             250.3        170.9          73.2         12.2
versicolor         296.8        138.5         213.0         66.3
virginica          329.4        148.7         277.6        101.3

In [405]:
obj.describe().T

species                setosa  versicolor  virginica
sepal_length count  50.000000   50.000000  50.000000
             mean    5.006000    5.936000   6.588000
             std     0.352490    0.516171   0.635880
             min     4.300000    4.900000   4.900000
             25%     4.800000    5.600000   6.225000
             50%     5.000000    5.900000   6.500000
             75%     5.200000    6.300000   6.900000
             max     5.800000    7.000000   7.900000
sepal_width  count  50.000000   50.000000  50.000000
             mean    3.418000    2.770000   2.974000
             std     0.381024    0.313798   0.322497
             min     2.300000    2.000000   2.200000
             25%     3.125000    2.525000   2.800000
             50%     3.400000    2.800000   3.000000
             75%     3.675000    3.000000   3.175000
             max     4.400000    3.400000   3.800000
petal_length count  50.000000   50.000000  50.000000
             mean    1.464000    4.260000   5.552000
             std     0.173511    0.469911   0.551895
             min     1.000000    3.000000   4.500000
             25%     1.400000    4.000000   5.100000
             50%     1.500000    4.350000   5.550000
             75%     1.575000    4.600000   5.875000
             max     1.900000    5.100000   6.900000
petal_width  count  50.000000   50.000000  50.000000
             mean    0.244000    1.326000   2.026000
             std     0.107210    0.197753   0.274650
             min     0.100000    1.000000   1.400000
             25%     0.200000    1.200000   1.800000
             50%     0.200000    1.300000   2.000000
             75%     0.300000    1.500000   2.300000
             max     0.600000    1.800000   2.500000

In [406]:
import warnings 
warnings.filterwarnings('ignore')

In [410]:
nan_idx = np.random.randint(0,20,20)

In [413]:
df.sepal_length[nan_idx] = np.nan

In [414]:
df

sepal_length  sepal_width  petal_length  petal_width    species
131           7.9          3.8           6.4          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
..            ...          ...           ...          ...        ...
41            4.5          2.3           1.3          0.3     setosa
8             NaN          2.9           1.4          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
42            4.4          3.2           1.3          0.2     setosa
13            NaN          3.0           1.1          0.1     setosa

[150 rows x 5 columns]

In [416]:
nan_idx = np.random.randint(0,50,15)

In [421]:
df.petal_length[nan_idx] = np.nan

In [422]:
df

sepal_length  sepal_width  petal_length  petal_width    species
131           7.9          3.8           6.4          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
..            ...          ...           ...          ...        ...
41            4.5          2.3           1.3          0.3     setosa
8             NaN          2.9           1.4          0.2     setosa
38            4.4          3.0           NaN          0.2     setosa
42            4.4          3.2           NaN          0.2     setosa
13            NaN          3.0           1.1          0.1     setosa

[150 rows x 5 columns]

In [424]:
df.isnull().sum()

sepal_length    12
sepal_width      0
petal_length    12
petal_width      0
species          0
dtype: int64

In [425]:
#df.dropna()

In [432]:
df.sepal_length.fillna(value=round(df.sepal_length.mean(), 1), inplace=True)

In [433]:
df

sepal_length  sepal_width  petal_length  petal_width    species
131           7.9          3.8           6.4          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
..            ...          ...           ...          ...        ...
41            4.5          2.3           1.3          0.3     setosa
8             5.9          2.9           1.4          0.2     setosa
38            4.4          3.0           NaN          0.2     setosa
42            4.4          3.2           NaN          0.2     setosa
13            5.9          3.0           1.1          0.1     setosa

[150 rows x 5 columns]

In [440]:
df.petal_length.fillna(value=round(df['petal_length'].median(),1), inplace=True)

In [441]:
df

sepal_length  sepal_width  petal_length  petal_width    species
131           7.9          3.8           6.4          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
..            ...          ...           ...          ...        ...
41            4.5          2.3           1.3          0.3     setosa
8             5.9          2.9           1.4          0.2     setosa
38            4.4          3.0           4.5          0.2     setosa
42            4.4          3.2           4.5          0.2     setosa
13            5.9          3.0           1.1          0.1     setosa

[150 rows x 5 columns]

In [444]:
df.petal_length[:10]

131    6.4
118    6.9
122    6.7
135    6.1
117    6.7
105    6.6
130    6.1
107    6.3
129    5.8
125    6.0
Name: petal_length, dtype: float64

In [446]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [449]:
new_df = pd.DataFrame(np.random.randint(0,100,size = (10,4)))

In [450]:
new_df

0   1   2   3
0  63  37  60  46
1  93  36  31  78
2  15  42  95  45
3  51  88  40  54
4  91  82  48  53
5  40  16  31  68
6  55   0  39  47
7  82  22  53  58
8  56  74   3  38
9   5  70  61  91

In [453]:
new_df['species'] = 'new_species'

In [454]:
new_df

0   1   2   3      species
0  63  37  60  46  new_species
1  93  36  31  78  new_species
2  15  42  95  45  new_species
3  51  88  40  54  new_species
4  91  82  48  53  new_species
5  40  16  31  68  new_species
6  55   0  39  47  new_species
7  82  22  53  58  new_species
8  56  74   3  38  new_species
9   5  70  61  91  new_species

In [455]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [457]:
new_df.columns = df.columns

In [458]:
new_df

sepal_length  sepal_width  petal_length  petal_width      species
0            63           37            60           46  new_species
1            93           36            31           78  new_species
2            15           42            95           45  new_species
3            51           88            40           54  new_species
4            91           82            48           53  new_species
5            40           16            31           68  new_species
6            55            0            39           47  new_species
7            82           22            53           58  new_species
8            56           74             3           38  new_species
9             5           70            61           91  new_species

In [459]:
df.shape

(150, 5)

In [460]:
new_df.shape

(10, 5)

In [463]:
pd.concat((df, new_df), axis=1)

sepal_length  sepal_width  petal_length  petal_width    species  \
0             5.1          3.5           1.4          0.2     setosa   
1             4.9          3.0           1.4          0.2     setosa   
2             5.9          3.2           1.3          0.2     setosa   
3             5.9          3.1           1.5          0.2     setosa   
4             5.0          3.6           4.5          0.2     setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     sepal_length  sepal_width  petal_length  petal_width      species  
0            63.0         37.0          60.0         46.0  new_species  
1            93.0         36.0          31.0         78.0  new_species  
2            15.0         42.0          95.0         45.0  new_species  
3            51.0         88.0          40.0         54.0  new_species  
4            91.0         82.0          48.0         53.0  new_species  
..            ...          ...           ...          ...          ...  
145           NaN          NaN           NaN          NaN          NaN  
146           NaN          NaN           NaN          NaN          NaN  
147           NaN          NaN           NaN          NaN          NaN  
148           NaN          NaN           NaN          NaN          NaN  
149           NaN          NaN           NaN          NaN          NaN  

[150 rows x 10 columns]

In [465]:
df1 = pd.DataFrame({'S_name':['Mohit', 'Jatin', 'Prateek', 'Mohit'], 
             'CGPA':[2,4,5,3]})

In [467]:
df2 = pd.DataFrame({'T_name':['Mohit', 'Jatin', 'Prateek', 'Mohit'], 
             'CGPA':[3,6,8,9]})

In [468]:
df1

S_name  CGPA
0    Mohit     2
1    Jatin     4
2  Prateek     5
3    Mohit     3

In [469]:

df2

T_name  CGPA
0    Mohit     3
1    Jatin     6
2  Prateek     8
3    Mohit     9

In [470]:
df1.merge(df2)

S_name  CGPA T_name
0  Mohit     3  Mohit

In [473]:
df1.merge(df2,how='left')  #{'left', 'right', 'outer', 'inner', 'cross'}

S_name  CGPA T_name
0    Mohit     2    NaN
1    Jatin     4    NaN
2  Prateek     5    NaN
3    Mohit     3  Mohit

In [474]:
df1.merge(df2, how='right')

S_name  CGPA   T_name
0  Mohit     3    Mohit
1    NaN     6    Jatin
2    NaN     8  Prateek
3    NaN     9    Mohit

In [475]:
df1.merge(df2, how='outer')

S_name  CGPA   T_name
0    Mohit     2      NaN
1    Jatin     4      NaN
2  Prateek     5      NaN
3    Mohit     3    Mohit
4      NaN     6    Jatin
5      NaN     8  Prateek
6      NaN     9    Mohit

In [476]:
df1.merge(df2, how='cross')

S_name  CGPA_x   T_name  CGPA_y
0     Mohit       2    Mohit       3
1     Mohit       2    Jatin       6
2     Mohit       2  Prateek       8
3     Mohit       2    Mohit       9
4     Jatin       4    Mohit       3
5     Jatin       4    Jatin       6
6     Jatin       4  Prateek       8
7     Jatin       4    Mohit       9
8   Prateek       5    Mohit       3
9   Prateek       5    Jatin       6
10  Prateek       5  Prateek       8
11  Prateek       5    Mohit       9
12    Mohit       3    Mohit       3
13    Mohit       3    Jatin       6
14    Mohit       3  Prateek       8
15    Mohit       3    Mohit       9

In [478]:
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [480]:
df.sort_index()

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             5.9          3.2           1.3          0.2     setosa
3             5.9          3.1           1.5          0.2     setosa
4             5.0          3.6           4.5          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [481]:
df.to_csv('modified2306.csv', index=False)

In [483]:
modified_df = pd.read_csv('modified2306.csv')

In [484]:
modified_df.head()

sepal_length  sepal_width  petal_length  petal_width    species
0           7.9          3.8           6.4          2.0  virginica
1           7.7          2.6           6.9          2.3  virginica
2           7.7          2.8           6.7          2.0  virginica
3           7.7          3.0           6.1          2.3  virginica
4           7.7          3.8           6.7          2.2  virginica

In [487]:
df.to_excel('myirisexcel.xlsx', index=False, sheet_name = 'iris_data')